### ISSUE TITLE
Can't get the mod to work

### ISSUE THREAD

**Issue by MoonSheid** [Killface1980/DualSense4Rockstar#15]
I've tried different versions of Script Hook RDR2 and ScriptHookRDR2DotNet V2, extracted them to the root folder of the game, and the mod in the folder "scripts", but I can't get it to work
What am I doing wrong?
The only thing I see is: **"Could not find a part of the path 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt'."**
And I really don't have that path, and neither does the file
Is there any way to create it, or maybe some dsx setting is responsible for this?

Here's the log from ScriptHookRDRDotNet.log

[22:16:10] [INFO] Config loaded from C:\Program Files\Games\RedDeadRedemption2\ScriptHookRDRDotNet.ini
[22:16:10] [DEBUG] Loading API from C:\Program Files\Games\RedDeadRedemption2\ScriptHookRDRNetAPI.dll ...
[22:16:10] [DEBUG] API from C:\Program Files\Games\RedDeadRedemption2\ScriptHookRDRNetAPI.dll loaded ...
[22:16:10] [DEBUG] Resolve handler removed
[22:16:11] [DEBUG] Loading scripts from C:\Program Files\Games\RedDeadRedemption2\scripts\ ...
[22:16:11] [DEBUG] Loading assembly DSX_Base.dll ...
[22:16:11] [INFO] Found 0 script(s) in DSX_Base.dll.
[22:16:11] [DEBUG] Loading assembly DualSense4RDR2.dll ...
[22:16:11] [DEBUG] compatibleApi resolved ScriptHookRDRNetAPI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
[22:16:11] [INFO] Found 2 script(s) in DualSense4RDR2.dll resolved to API 2.0.0.
[22:16:11] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[22:16:11] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[22:16:11] [DEBUG] Instantiating script DualSense4RDR2.LEDs_RDR2 ...
[22:16:11] [INFO] Started script DualSense4RDR2.LEDs_RDR2.
[22:16:11] [DEBUG] Instantiating script DualSense4RDR2.Main_RDR2 ...
[22:16:11] [ERROR] Failed to instantiate script DualSense4RDR2.Main_RDR2 because constructor threw an exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at DSX_Base.Client.iO.Connect()
   at DualSense4RDR2.Main_RDR2..ctor()
[22:16:11] [ERROR] Caught fatal unhandled exception:
System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at DSX_Base.Client.iO.Send(Packet data)
   at DualSense4RDR2.LEDs_RDR2.SendPacketRGB(Single red, Single green, Single blue)
   at DualSense4RDR2.LEDs_RDR2.HandleLEDs()
   at DualSense4RDR2.LEDs_RDR2.OnTick(Object sender, EventArgs e)
   at RDR2DN.Script.MainLoop()
[22:16:11] [ERROR] The exception was thrown while executing the script DualSense4RDR2.LEDs_RDR2.
[22:16:11] [WARNING] Aborted script DualSense4RDR2.LEDs_RDR2.

**Comment by Kike096** [comment]
I have the same problem! could you solve it? Please help!!

**Comment by HuRongchuan** [comment]
this video  can solve the problem, look at the top comment.
【[pc]荒野大镖客2自适应扳机MOD安装使用教程-PC5手柄】 https://www.bilibili.com/video/BV1bT41197Fx/?share_source=copy_web&vd_source=b0cc56a4f744d80a94723ba127a2f2b4

**Comment by HuRongchuan** [comment]
> I have the same problem! could you solve it? Please help!!

【[pc]荒野大镖客2自适应扳机MOD安装使用教程-PC5手柄】 https://www.bilibili.com/video/BV1bT41197Fx/?share_source=copy_web&vd_source=b0cc56a4f744d80a94723ba127a2f2b4
