### ISSUE TITLE
GTAV: Leds not working (scripts didn't start due to exception)

### ISSUE THREAD

**Issue by WitcherTro** [Killface1980/DualSense4Rockstar#24]
Adaptive triggers do seem to be working, but leds script won't due to wrong string format.

SHVDN log:
       [INFO] Started script DualSense4GTAV.add.
       [ERROR] Caught fatal unhandled exception:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at DualSense4GTAV.iO.Connect()
   at DualSense4GTAV.iO.GetStat(Int32& bat, Boolean& isConnected)
   at DualSense4GTAV.LEDs_GTAV.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
       [ERROR] The exception was thrown while executing the script DualSense4GTAV.LEDs_GTAV.
       [WARNING] Aborted script DualSense4GTAV.LEDs_GTAV.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()
       [ERROR] Caught fatal unhandled exception:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at DualSense4GTAV.add.Connect()
   at DualSense4GTAV.add.onTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
        [ERROR] The exception was thrown while executing the script DualSense4GTAV.add.
        [WARNING] Aborted script DualSense4GTAV.add.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()
        [ERROR] Caught unhandled exception:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at DualSense4GTAV.iO.Connect()
   at DualSense4GTAV.iO.GetStat(Int32& bat, Boolean& isConnected)
   at DualSense4GTAV.Config.ControllerConfig.OnKeyDown(Object sender, KeyEventArgs e)
   at SHVDN.Script.DoTick()
        [ERROR] The exception was thrown while executing the script DualSense4GTAV.Main_GTAV.

**Comment by WitcherTro** [comment]
Fixed by manually writing port number inside C:\Temp\DualSenseX\DualSenseX_PortNumber.txt
