### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by smashkanthegreat** [Killface1980/DualSense4Rockstar#27]
Mod works! I'm getting haptic feedback, but for some reason the menu does not work. When I hit the function key, I get the following:

[17:03:31] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[17:03:31] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[17:03:31] [DEBUG] Loading scripts from C:\Program Files\Epic Games\GTAV\scripts ...
[17:03:32] [DEBUG] Loading assembly DSX_Base.dll ...
[17:03:32] [INFO] Found 0 script(s) in DSX_Base.dll.
[17:03:32] [DEBUG] Loading assembly DualSense4GTAV.dll ...
[17:03:32] [INFO] Found 3 script(s) in DualSense4GTAV.dll resolved to API 3.6.0.
[17:03:32] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[17:03:32] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[17:03:32] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[17:03:32] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[17:03:32] [DEBUG] Instantiating script DualSense4GTAV.LEDs_GTAV ...
[17:03:32] [INFO] Started script DualSense4GTAV.LEDs_GTAV.
[17:03:32] [DEBUG] Instantiating script DualSense4GTAV.Main_GTAV ...
[17:03:34] [INFO] Started script DualSense4GTAV.Main_GTAV.
[17:03:34] [DEBUG] Instantiating script DualSense4GTAV.add ...
[17:03:34] [INFO] Started script DualSense4GTAV.add.
[17:03:34] [ERROR] Caught fatal unhandled exception:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at DualSense4GTAV.iO.Connect()
   at DualSense4GTAV.iO.GetStat(Int32& bat, Boolean& isConnected)
   at DualSense4GTAV.LEDs_GTAV.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[17:03:34] [ERROR] The exception was thrown while executing the script DualSense4GTAV.LEDs_GTAV.
[17:03:34] [WARNING] Aborted script DualSense4GTAV.LEDs_GTAV.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()
[17:03:34] [ERROR] Caught fatal unhandled exception:
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at DualSense4GTAV.add.Connect()
   at DualSense4GTAV.add.onTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[17:03:34] [ERROR] The exception was thrown while executing the script DualSense4GTAV.add.
[17:03:34] [WARNING] Aborted script DualSense4GTAV.add.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()

Honestly debatable whether troubleshooting is worth the time, so no rush. I'm having fun with the mod, I'm just stubborn and curious. Thanks in advance for taking a look.

**Comment by JMZ10** [comment]
I am seeing the same error on my installation,, like dead identical, so I too am curious.

**Comment by Killface1980** [comment]
I guess the mod is looking for a text file.
Currently updating the mod, In the mean time try following this topic:

https://github.com/Killface1980/DualSense4Rockstar/issues/28#issuecomment-2032155387

**Comment by Killface1980** [comment]
Duplicate of #15

**Comment by tommargar** [comment]
Solved with the 2024 update branch.

**Comment by smashkanthegreat** [comment]
Amazing! I don't currently have my games installed, I go through gaming phases. Yours was my fav haptic feedback mod and worked great even before the fix. I'll reinstall and check it out again over the holidays. Always a fan of elegant coding and your mod is great. Thanks so much!
