### ISSUE TITLE
Possible issue when running mod but no dualsense connected/dsx running

### ISSUE THREAD

**Issue by dfgdgdgfd** [Killface1980/DualSense4Rockstar#5]
I've done this several times with gta v and never had a problem but did today.  The actual error and my scripthook log: [https://imgur.com/a/vMbBPt7](url)

[04:35:33] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[04:35:33] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[04:35:33] [DEBUG] Loading scripts from H:\Gta 1.58 work\scripts ...
[04:35:33] [DEBUG] Loading assembly Advanced Bodyguards.dll ...
[04:35:33] [INFO] Found 1 script(s) in Advanced Bodyguards.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly AMLSNativeUI.dll ...
[04:35:33] [INFO] Found 1 script(s) in AMLSNativeUI.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly DSX_Base.dll ...
[04:35:33] [INFO] Found 0 script(s) in DSX_Base.dll.
[04:35:33] [DEBUG] Loading assembly DualSense4GTAV.dll ...
[04:35:33] [INFO] Found 3 script(s) in DualSense4GTAV.dll resolved to API 3.5.1.
[04:35:33] [DEBUG] Loading assembly GangMod.dll ...
[04:35:33] [INFO] Found 17 script(s) in GangMod.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[04:35:33] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[04:35:33] [DEBUG] Loading assembly Mission Maker.dll ...
[04:35:33] [INFO] Found 2 script(s) in Mission Maker.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly NativeUI.dll ...
[04:35:33] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly NAudio.dll ...
[04:35:33] [INFO] Found 0 script(s) in NAudio.dll.
[04:35:33] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[04:35:33] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[04:35:33] [DEBUG] Loading assembly passengermod.dll ...
[04:35:33] [INFO] Found 1 script(s) in passengermod.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Loading assembly RadarZoom.dll ...
[04:35:33] [WARNING] Resolving API version 0.0.0 referenced in RadarZoom.dll.
[04:35:33] [INFO] Found 1 script(s) in RadarZoom.dll resolved to API 2.11.5.
[04:35:33] [DEBUG] Instantiating script AdvancedBodyguards ...
[04:35:35] [INFO] Started script AdvancedBodyguards.
[04:35:35] [DEBUG] Instantiating script AMLSNativeUI.AMLSBigMessageThread ...
[04:35:35] [INFO] Started script AMLSNativeUI.AMLSBigMessageThread.
[04:35:35] [DEBUG] Instantiating script BetterPassengerMod.PassengerMod ...
[04:35:35] [INFO] Started script BetterPassengerMod.PassengerMod.
[04:35:35] [DEBUG] Instantiating script DualSense4GTAV.Main_GTAV ...
[04:35:35] [INFO] Started script DualSense4GTAV.Main_GTAV.
[04:35:35] [DEBUG] Instantiating script DualSense4GTAV.Main_LEDs.Main_LEDs ...
[04:35:35] [INFO] Started script DualSense4GTAV.Main_LEDs.Main_LEDs.
[04:35:35] [DEBUG] Instantiating script GangMod.GangBackup ...
[04:35:35] [INFO] Started script GangMod.GangBackup.
[04:35:35] [DEBUG] Instantiating script GangMod.GangBrawl ...
[04:35:35] [INFO] Started script GangMod.GangBrawl.
[04:35:35] [DEBUG] Instantiating script GangMod.GangDragHomie ...
[04:35:35] [INFO] Started script GangMod.GangDragHomie.
[04:35:35] [DEBUG] Instantiating script GangMod.GangDriveby ...
[04:35:35] [INFO] Started script GangMod.GangDriveby.
[04:35:35] [DEBUG] Instantiating script GangMod.GangEventDestroyVehicle ...
[04:35:35] [INFO] Started script GangMod.GangEventDestroyVehicle.
[04:35:35] [DEBUG] Instantiating script GangMod.GangEventDriveby ...
[04:35:35] [INFO] Started script GangMod.GangEventDriveby.
[04:35:35] [DEBUG] Instantiating script GangMod.GangEvents ...
[04:35:35] [INFO] Started script GangMod.GangEvents.
[04:35:35] [DEBUG] Instantiating script GangMod.GangEventStoreRobbery ...
[04:35:35] [INFO] Started script GangMod.GangEventStoreRobbery.
[04:35:35] [DEBUG] Instantiating script GangMod.GangHUD ...
[04:35:35] [INFO] Started script GangMod.GangHUD.
[04:35:35] [DEBUG] Instantiating script GangMod.GangInteraction ...
[04:35:35] [INFO] Started script GangMod.GangInteraction.
[04:35:35] [DEBUG] Instantiating script GangMod.GangModInteractionMenu ...
[04:35:35] [INFO] Started script GangMod.GangModInteractionMenu.
[04:35:35] [DEBUG] Instantiating script GangMod.GangRecruitMember ...
[04:35:35] [INFO] Started script GangMod.GangRecruitMember.
[04:35:35] [DEBUG] Instantiating script GangMod.GangRelationships ...
[04:35:35] [INFO] Started script GangMod.GangRelationships.
[04:35:35] [DEBUG] Instantiating script GangMod.GangSelector ...
[04:35:35] [INFO] Started script GangMod.GangSelector.
[04:35:35] [DEBUG] Instantiating script GangMod.GangWar ...
[04:35:35] [INFO] Started script GangMod.GangWar.
[04:35:35] [DEBUG] Instantiating script GangMod.Main ...
[04:35:35] [INFO] Started script GangMod.Main.
[04:35:35] [DEBUG] Instantiating script GangMod.Settings ...
[04:35:35] [INFO] Started script GangMod.Settings.
[04:35:35] [DEBUG] Instantiating script Mission_Maker11_10_20171 ...
[04:35:35] [INFO] Started script Mission_Maker11_10_20171.
[04:35:35] [DEBUG] Instantiating script Mission_Maker11_10_20171+RandomSpawnThread ...
[04:35:35] [INFO] Started script Mission_Maker11_10_20171+RandomSpawnThread.
[04:35:35] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[04:35:35] [INFO] Started script NativeUI.BigMessageThread.
[04:35:35] [DEBUG] Instantiating script RadarZoom ...
[04:35:35] [INFO] Started script RadarZoom.
[04:35:36] [DEBUG] Instantiating script DualSense4GTAV.add ...
[04:35:36] [INFO] Started script DualSense4GTAV.add.
[04:36:29] [ERROR] Caught fatal unhandled exception:
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at DualSense4GTAV.iO.GetStat(Int32& bat, Boolean& isConnected)
   at DualSense4GTAV.Main_LEDs.Main_LEDs.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[04:36:29] [ERROR] The exception was thrown while executing the script DualSense4GTAV.Main_LEDs.Main_LEDs.
[04:36:29] [WARNING] Aborted script DualSense4GTAV.Main_LEDs.Main_LEDs.

**Comment by Killface1980** [comment]
Maybe there is another network session open? Have you tried restarting DSX and/or your computer to get the leftovers out of the memory?

**Comment by Killface1980** [comment]
Updated in the __Release folder. I've added an additional check if the Sockets throw any errors. Should be fixed and show the disconnected status.

**Comment by dfgdgdgfd** [comment]
I also still had the "script loaded but dsx is not running" message constantly, but no f10 prompt to hide it.

**Comment by Killface1980** [comment]
Updated, the mod should now shutdown itself if it loses connection. Mod will be reactivated by F8 (menu key),

**Comment by dfgdgdgfd** [comment]
This version has caused a new issue - when firing a gun the game will freeze and unfreeze, and dsx will keep disconnecting and reconnecting the controller.  This also happened on the gta v mod that yours is based off of.

**Comment by Killface1980** [comment]
I couldn't replicate the issue. Are you using the Steam version of DSX or the free version?

**Comment by dfgdgdgfd** [comment]
Steam.  I used a utility that deletes drivers for devices that aren't currently plugged in, I had many, many hid devices which I'm guessing were unsuccessful pairs with bluetooth.  I'm using a usb receiver, are you meant to unpair a bluetooth device before unplugging this receiver or moving it to another port?  It seems like the controller won't be seen as the same device unless I unpair, with a usb cable I never have this issue.

**Comment by Killface1980** [comment]
I can't tell. I've disabled my on board bluetooth and reenabled it several times, with the mod behaving as expected and no stutter or freezing while firing. The code has most likely the same impact on performance if the player is in a vehicle. 
I'm generally disabling my bluetooth device to disconnect all devices. Headphones etc. are recognized when disabling, possible that Windos or some driver pass a new controller id. Had an issue with TMNT a while ago where my controller was recognized as #2, #3 etc. if some other program crashed. 
I'm also using Steam with a custom controller layout to use Gyro for aiming, maybe the emulation helps? Other apps like DS4Windows might also interfer and caused only trouble here.
